//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GenericRepoWebApp.Data.DataAccess.SqlServer
{
    public partial class Bar
    {
        public int BarId { get; set; }
        public string BarName { get; set; }
    }
    
}
